const recipes = [
  {
    name: "Spaghetti and Meatballs",
    description:
      "Making your sauce is always better—it's cheaper and so much more flavorful. This one comes together in about 15 minutes and is the perfect accompaniment to the big garlicky meatballs.",
    src: "/spaghetti-and-meatballs.png",
    ingredients: [
      "1 lb. spaghetti",
      "1 lb. ground beef",
      "1/3 c. bread crumbs",
      "1/4 c. finely chopped parsley",
      "1/4 c. freshly grated Parmesan, plus more for serving",
      "1 egg",
      "2 garlic cloves, minced",
      "Kosher salt",
      "1/2 tsp. red pepper flakes",
      "2 tbsp. extra-virgin olive oil",
      "1/2 c. onion, finely chopped",
      "1 (28-oz.) can crushed tomatoes",
      "1 bay leaf",
      "Freshly ground black pepper",
    ],
    directions: [
      "\n          In a large pot of boiling salted water, cook spaghetti according to\n          package instructions. Drain.\n        ",
      "\n          In a large bowl, combine beef with bread crumbs, parsley, Parmesan,\n          egg, garlic, 1 teaspoon salt, and red pepper flakes. Mix until just\n          combined then form into 16 balls.\n        ",
      "\n          In a large pot over medium heat, heat oil. Add meatballs and cook,\n          turning occasionally, until browned on all sides, about 10 minutes.\n          Transfer meatballs to a plate.\n        ",
      "\n          Add onion to pot and cook until soft, 5 minutes. Add crushed tomatoes\n          and bay leaf. Season with salt and pepper and bring to a simmer.\n          Return meatballs to pot and cover. Simmer until sauce has thickened, 8\n          to 10 minutes.\n        ",
      "\n          Serve pasta with a healthy scoop of meatballs and sauce. Top with\n          Parmesan before serving.\n        ",
    ],
  },
  {
    name: "Spiced Beef & Bucatini Pasta",
    description:
      "To add exciting contrast of flavor to this comforting pasta, you’ll cook ground beef with plump, sweet currants and briny capers in a bright sauce flavored with the quatre épices spice blend.",
    src: "/pasta.png",
    ingredients: [
      "1 1/8 lbs Ground Beef",
      "3/4 lb Bucatini Pasta",
      "1 Yellow Onion",
      "2 Zucchini",
      "5 oz Baby Spinach",
      "2 cloves Garlic",
      "1 Tbsp Capers",
      "2 Tbsps Dried Currants",
      "2 Tbsps Tomato Paste",
      "2 Tbsps Crème Fraîche",
      "1/4 cup Grated Parmesan Cheese",
      "1 1/2 tsps Calabrian Chile Paste",
      "2 Tbsps Butter",
      "1 tsp Quatre Épices (White Pepper, Nutmeg, Ginger &amp; Cloves)",
    ],
    directions: [
      "\n          Fill a large pot 3/4 of the way up with salted water; cover and heat\n          to boiling on high. Wash and dry the fresh produce. Medium dice the\n          zucchini. Halve, peel, and thinly slice the onion. Peel and roughly\n          chop 2 cloves of garlic. Place the currants in a bowl; cover with 1/4\n          cup of hot water. Set aside to rehydrate at least 10 minutes.\n        ",
      "\n          Add the pasta to the pot of boiling water. Cook, stirring\n          occasionally, 6 to 8 minutes, or until al dente (still slightly firm\n          to the bite). Turn off the heat. Reserving 1 cup of the pasta cooking\n          water, drain thoroughly and return to the pot.\n        ",
      "\n          Meanwhile, in a large pan (nonstick, if you have one), heat a drizzle\n          of olive oil on medium-high until hot. Add the diced zucchini in an\n          even layer; season with salt and pepper. Cook, without stirring, 3 to\n          4 minutes, or until browned. Continue to cook, stirring occasionally,\n          2 to 3 minutes, or until softened. Transfer to a plate and cover with\n          foil to keep warm. Wipe out the pan.\n        ",
      "\n          In the same pan, heat a drizzle of olive oil on medium-high until hot.\n          Add the beef, sliced onion, chopped garlic, capers, and quatre épices;\n          season with salt and pepper. Cook, stirring frequently and breaking\n          the meat apart with a spoon, 4 to 5 minutes, or until lightly browned.\n          Add the tomato paste and chile paste; season with salt and pepper.\n          Cook, stirring constantly, 1 to 2 minutes, or until thoroughly\n          combined. Add the spinach, 1/2 cup of water (carefully, as the liquid\n          may splatter), and rehydrated currants (including the liquid); season\n          with salt and pepper. Cook, stirring occasionally, 2 to 3 minutes, or\n          until the sauce is slightly thickened and the beef is cooked through.\n          Turn off the heat.\n        ",
      "\n          To the pot of cooked pasta, add the cooked beef and sauce, browned\n          zucchini, butter, and half the reserved pasta cooking water. Cook on\n          medium-high, stirring constantly, 1 to 2 minutes, or until the pasta\n          is coated (if necessary, gradually add the remaining cooking water to\n          ensure the pasta is thoroughly coated). Turn off the heat. Stir in the\n          crème fraîche until combined. Taste, then season with salt and pepper\n          if desired. Serve the finished pasta garnished with the cheese. Enjoy!\n        ",
    ],
  },
  {
    name: "Steamed Bao Buns",
    description:
      "The bao buns themselves are soft and puffy. Stuffed with zesty marinated tempeh, avocado, and lots of fresh fixings, they become mini explosions of texture and flavor.",
    src: "/bao.png",
    ingredients: [
      "2 teaspoons active dry yeast",
      "2 tablespoons sugar",
      "1/2 cup + 2 tablespoons warm water, 110°",
      "2 1/2 cups all-purpose flour",
      "1/2 teaspoon baking powder",
      "1/2 teaspoon baking soda",
      "2 teaspoons sea salt",
      "3/4 cup avocado oil, more for brushing",
      "8 ounces tempeh, sliced into 12 strips and steamed",
      "6 tablespoons hoisin sauce",
      "3 tablespoons sriracha",
      "1 teaspoon grated fresh ginger",
      "1 teaspoon lime zest",
      "Avocado slices",
      "Sliced cucumber and/or carrot",
      "Mint or cilantro",
      "Diced Thai chiles",
      "Lime wedges, for serving",
    ],
    directions: [
      "\n          Make the Bao Buns. In a small bowl, combine the yeast, sugar, and\n          water and stir. Set aside for 5 minutes, or until the yeast is foamy.\n        ",
      "\n          In a large bowl, combine the flour, baking powder, baking soda, and\n          salt. Add the avocado oil and the yeast mixture and mix to form a\n          rough ball, adding 1 to 2 tablespoons more water if the dough is too\n          dry. Transfer to a lightly floured surface, shape into a ball, and\n          vigorously knead it until it’s smooth and elastic, about 5 minutes.\n        ",
      "\n          Brush the inside of a bowl with a little oil and place the dough\n          inside. Cover and set it aside in a warm place for 45 minutes. (Note:\n          it won’t rise as much as other traditional yeasted doughs.)\n        ",
      "\n          Make the tempeh filling. Preheat the oven to 425°F and line a baking\n          sheet with parchment paper. In a small bowl, whisk together the hoisin\n          sauce, sriracha, ginger, and lime zest. Reserve half of the sauce for\n          serving and toss the remaining half with the tempeh slices and set\n          aside for 20 minutes to marinate. Place the tempeh on the baking sheet\n          and bake for 10 to 12 minutes or until browned around the edges.\n        ",
      "\n          Finish the buns. Cut twelve 4-inch squares of parchment paper and\n          place them on a large baking sheet. Transfer the dough to a clean work\n          surface and roll out evenly to ¼ inch thickness. Use a 3-inch glass to\n          cut out circles of dough and place them on the paper squares. Brush\n          the tops with a little oil, then fold each circle in half and gently\n          press down, flattening just a bit so that the halves stick together\n          but you still have a puffy bun shape. Cover with plastic wrap and let\n          rest for 1 hour, until puffed. Transfer to a bamboo steamer set over a\n          pan with 1-inch water. Bring the water to a simmer, cover, and steam\n          until puffed, 9 to 11 minutes. Work in batches.\n        ",
      "\n          Assemble. Squeeze a little lime juice over the avocado, cucumber, and\n          carrot. Assemble each bun with the tempeh, spooning a little sauce\n          over each tempeh piece, the avocado, veggies, herbs, and chiles. Serve\n          with remaining sauce on the side and lime slices for squeezing.\n        ",
    ],
  },
];

export default recipes;
